markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Ryan Sylvestre
production_url : http://ryansylvestre.com
description: ""
disqus_shortname: ryansylvestreblog
analytics: UA-41112651-1
author :
  name : Ryan Sylvestre
  github : ryansylvestre
  linkedin : ryansylvestre
  google : 114081915677587292812
  twitter : ryansylvestre
  email: rjsylvestre@gmail.com
